DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS "workOrders" CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS receives CASCADE;
DROP TABLE IF EXISTS returns CASCADE;
DROP TABLE IF EXISTS delivery_notes CASCADE;
DROP TABLE IF EXISTS shipping_addresses CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;

-- 1. users
CREATE TABLE users (
  id BIGINT PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  name TEXT
);

-- 2. admins
CREATE TABLE admins (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL
);

-- 3. departments
CREATE TABLE departments (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL
);

-- 4. employees
CREATE TABLE employees (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  dept TEXT
);

-- 5. workOrders
CREATE TABLE "workOrders" (
  id BIGINT PRIMARY KEY,
  code TEXT,
  project TEXT
);

-- 6. items
CREATE TABLE items (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  unit TEXT,
  "minStock" NUMERIC DEFAULT 0,
  stock NUMERIC DEFAULT 0,
  category TEXT,
  photo TEXT,
  "itemCode" TEXT,
  "averageCost" NUMERIC DEFAULT 0,
  "lastPrice" NUMERIC DEFAULT 0,
  "totalValue" NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 7. transactions
CREATE TABLE transactions (
  id BIGINT PRIMARY KEY,
  taker TEXT,
  dept TEXT,
  "workOrder" TEXT,
  note TEXT,
  date TEXT,
  time TEXT,
  admin TEXT,
  items JSONB NOT NULL,
  "approvalStatus" TEXT,
  "approvalNote" TEXT,
  "approvedBy" TEXT,
  "approvedAt" TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 8. receives
CREATE TABLE receives (
  id BIGINT PRIMARY KEY,
  "itemId" BIGINT,
  "itemName" TEXT,
  unit TEXT,
  qty NUMERIC,
  "poNumber" TEXT,
  "doNumber" TEXT,
  date TEXT,
  admin TEXT,
  time TEXT,
  "buyPrice" NUMERIC DEFAULT 0,
  attachment TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 9. returns
CREATE TABLE returns (
  id BIGINT PRIMARY KEY,
  employee TEXT,
  "itemId" BIGINT,
  "itemName" TEXT,
  unit TEXT,
  qty NUMERIC,
  reason TEXT,
  note TEXT,
  date TEXT,
  time TEXT,
  status TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 10. delivery_notes
CREATE TABLE delivery_notes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  batch TEXT,
  category TEXT,
  date TEXT,
  project_no TEXT,
  no_kendaraan TEXT,
  destination TEXT,
  attn TEXT,
  full_address TEXT,
  items JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 11. shipping_addresses
CREATE TABLE shipping_addresses (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  destination TEXT,
  attn TEXT,
  contact TEXT,
  full_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 12. audit_logs
CREATE TABLE audit_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  action TEXT,
  actor JSONB,
  target TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Disable Row Level Security (RLS) on all tables for public development access
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE admins DISABLE ROW LEVEL SECURITY;
ALTER TABLE departments DISABLE ROW LEVEL SECURITY;
ALTER TABLE employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE "workOrders" DISABLE ROW LEVEL SECURITY;
ALTER TABLE items DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE receives DISABLE ROW LEVEL SECURITY;
ALTER TABLE returns DISABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE shipping_addresses DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;
